import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body 
      className="min-h-full flex flex-col">
        <header className="flex items-center gap-4 bg-white p-4 shadow">
          <a href="/" className="font-bold">🏠 ホーム</a>
          <a href="/quizzes">📚 クイズ一覧</a>
          <a href="/admin/create-quiz">➕ クイズ作成</a>
          <a href="/admin/quizzes">🛠 管理</a>
        </header>
        {children}
      </body>
    </html>
  );
}
